package main

import (
	"fmt"
	"reflect"

	"github.com/fatih/color"
)

type Condition interface {
	Score() bool
	// for autogenerated check messaged
	DefaultString() string
}

type Check struct {
	Message string
	Points  int
	// points were left unspecified
	PointsEmpty bool

	// the root condition can have a hint
	Condition

	// separate root hint from condition tree
	Hint string
}

func (c *Check) Debug() string {
	cl := color.New(color.Bold)
	ret := cl.Sprintf("%s (%d Points)%s\n", c.Message, c.Points, formatHint(c.Hint))
	return ret + DebugCondition(c.Condition)
}

type Parser struct {
	Lexer          *Lexer
	Lookahead      *Token
	LookaheadValid bool
	// currently-parsing check message; used for debugging
	CurrentCheckMessage string
}

func NewParser(lexer *Lexer) *Parser {
	return &Parser{Lexer: lexer, Lookahead: nil, LookaheadValid: false, CurrentCheckMessage: "N/A"}
}

func (p *Parser) Peek() *Token {
	if !p.LookaheadValid {
		p.Lookahead = p.Lexer.NextToken()
		p.LookaheadValid = true
	}
	return p.Lookahead
}

func (p *Parser) Consume() *Token {
	token := p.Peek()
	p.LookaheadValid = false
	return token
}

func (p *Parser) SkipTokenType(tokenType TokenType) {
	for {
		token := p.Peek()
		if token.Type != tokenType {
			break
		}
		p.Consume()
	}
}

func (p *Parser) SkipWhitespace() {
	for {
		token := p.Peek()
		if token.Type != TokenNewline && token.Type != TokenIndent {
			break
		}
		p.Consume()
	}
}

func (p *Parser) SkipUntilIndentedBlock() bool {
	for {
		token := p.Peek()
		if token.Type == TokenNewline {
			p.Consume()
			token = p.Peek()
			if token.Type != TokenNewline && token.Type != TokenIndent {
				return false
			}
		} else if token.Type == TokenIndent {
			p.Consume()
			if p.Peek().Type == TokenNewline {
				p.Consume()
			} else {
				// reached non-newline token after indent
				return true
			}
		} else {
			return true
		}
	}
}

// skip newline and indent if a check is hanging onto the next line
// (e.g. the boolean operator terminates the line)
// for example:
//
//	PathExists "/abc" ||
//	FileContains "abc" "abc"
func (p *Parser) SkipIndentIfHanging() {
	if !p.SkipUntilIndentedBlock() {
		p.Errorf("unterminated hanging boolean operator for check: '%s'", p.CurrentCheckMessage)
	}
}

func (p *Parser) Errorf(format string, a ...any) {
	message := fmt.Sprintf(format, a...)
	line, column := p.Lexer.GetSourceVisualLocation()
	Fatal(STAGE_PARSER, fmt.Sprintf("(line %d, column %d) %s", line, column, message))
}

func (p *Parser) ExpectTokenType(tokenType TokenType, msg string) *Token {
	nextToken := p.Consume()
	if nextToken.Type != tokenType {
		p.Errorf("expected token of type '%s', got '%s' (type '%s'): %s",
			tokenType.Str(), nextToken.Value(), nextToken.Type.Str(), msg)
		return nil // unreachable
	}
	return nextToken
}

func (p *Parser) ExpectTokenType2(tokenType1 TokenType, tokenType2 TokenType, msg string) *Token {
	nextToken := p.Consume()
	if nextToken.Type != tokenType1 && nextToken.Type != tokenType2 {
		p.Errorf("expected token of type '%s' or '%s', got '%s' (type '%s'): %s",
			tokenType1.Str(), tokenType2.Str(), nextToken.Value(), nextToken.Type.Str(), msg)
		return nil // unreachable
	}
	return nextToken
}

func (p *Parser) MaybeParseHint() string {
	if p.Peek().Type == TokenLBracket {
		// assume LBracket ([) has been peeked
		p.Consume()
		hintString := p.ExpectTokenType(
			TokenString,
			"expected string inside after opening left-brace ([) denoting the beginning of a hint",
		)
		p.ExpectTokenType(
			TokenRBracket,
			fmt.Sprintf("expecting closing right-brace (]) for hint: %s", hintString.Value()),
		)
		return hintString.Value().(string)
	}
	return ""
}

func (p *Parser) ParseCondition() Condition {
	lhs := p.ParseAnd()
	for p.Peek().Type == TokenOr {
		p.Consume()
		p.SkipIndentIfHanging()

		rhs := p.ParseAnd()
		lhs = &OrExpr{Lhs: lhs, Rhs: rhs}
	}
	return lhs
}

func (p *Parser) ParseAnd() Condition {
	lhs := p.ParseFactor()
	for p.Peek().Type == TokenAnd {
		p.Consume()
		p.SkipIndentIfHanging()

		rhs := p.ParseFactor()
		lhs = &AndExpr{Lhs: lhs, Rhs: rhs}
	}
	return lhs
}

func (p *Parser) ParseFactor() Condition {
	next := p.Peek()

	var cond Condition
	if next.Type == TokenLParen {
		p.Consume()
		cond = p.ParseCondition()
		p.ExpectTokenType(
			TokenRParen,
			fmt.Sprintf("expected closing right parenthese for condition for check: '%s'", p.CurrentCheckMessage),
		)
	} else if next.Type == TokenIdent {
		cond = p.ParseFunc()
	} else {
		p.Errorf(
			"invalid boolean expression for check '%s': expected function or parenthesized expression, got '%s'",
			p.CurrentCheckMessage,
			next.Debug(),
		)
	}

	hint := p.MaybeParseHint()
	if len(hint) != 0 {
		SetConditionHint(cond, hint)
	}
	return cond
}

func (p *Parser) ParseFunc() Condition {
	funcName := p.Consume().Value().(string)
	if len(funcName) <= len("Not") {
		p.Errorf("invalid check name: %s", funcName)
	}

	notFunc := false
	notIdx := len(funcName) - 3
	if funcName[notIdx:] == "Not" {
		notFunc = true
		funcName = funcName[:notIdx]
	}

	funcType, found := funcRegistry[funcName]
	if !found {
		p.Errorf("invalid function name: %s", funcName)
	}
	numArgs := funcType.NumField()

	ptr := reflect.New(funcType)
	elem := ptr.Elem()

	// Skip "BaseCondition" field
	for i := 1; i < numArgs; i++ {
		field := funcType.Field(i)
		arg := p.ExpectTokenType(
			TokenString,
			fmt.Sprintf(
				"expected argument for condition '%s': '%s' (at %d out of %d total arguments)",
				funcName,
				field.Name,
				i,
				numArgs,
			),
		).Value().(string)

		elem.Field(i).SetString(arg)
	}

	fun := ptr.Interface().(Condition)

	if notFunc {
		return &NotFunc{Func: fun}
	}
	return fun
}

func (p *Parser) NextCheck() *Check {
	p.SkipWhitespace()

	// current check has empty message; avoids any "magic" generation-needing message
	currentCheckMessageEmpty := false

	// parse check name
	if p.Peek().Type == TokenUnderscore {
		p.CurrentCheckMessage = "<anonymous>"
		currentCheckMessageEmpty = true
		p.Consume()
	} else {
		p.CurrentCheckMessage = p.ExpectTokenType(
			TokenString,
			"expected check title as a string or placeholder ('_')",
		).Value().(string)
	}

	p.ExpectTokenType(
		TokenColon,
		fmt.Sprintf("expected a colon following the check message: '%s'", p.CurrentCheckMessage),
	)

	// parse points
	points := 0
	pointsEmpty := false
	// if point number isn't a placeholder
	if p.Peek().Type == TokenUnderscore {
		pointsEmpty = true
		p.Consume()
	} else {
		points = p.ExpectTokenType(
			TokenNumber,
			fmt.Sprintf("expected integer point value or placeholder ('_') to follow colon for check: '%s'",
				p.CurrentCheckMessage),
		).Value().(int)
	}

	// parse hint if it exists
	rootHint := p.MaybeParseHint()

	var finalCond Condition
	// if single-line check
	if p.Peek().Type == TokenSemicolon {
		p.Consume()
		finalCond = p.ParseCondition()
	} else {
		var andedConditions []Condition
		for p.SkipUntilIndentedBlock() && p.Peek().Type != TokenEOF {
			cond := p.ParseCondition()
			andedConditions = append(andedConditions, cond)
		}

		// no conditions parsed
		if len(andedConditions) == 0 {
			p.Errorf(
				"unexpected end of file: expected an indented condition block for check '%s'",
				p.CurrentCheckMessage,
			)
		}

		finalCond = BuildAndTree(andedConditions)
	}

	checkString := p.CurrentCheckMessage
	if currentCheckMessageEmpty {
		checkString = finalCond.DefaultString()
	}

	return &Check{Message: checkString, Points: points, PointsEmpty: pointsEmpty, Condition: finalCond, Hint: rootHint}
}

func (p *Parser) Checks() []*Check {
	var checks []*Check
	for p.Peek().Type != TokenEOF {
		checks = append(checks, p.NextCheck())
	}
	return checks
}
